# Python Program To Build a student marksheet 
print("ABC school student marksheet.".title())
syd_name=input("enter your student name: ")
ft_name=input("enter student's father name: ")
clas=input("enter student's class: ")
rol_no=input("enter student's roll number: ")
print(("student name : "+syd_name).title())
print(("father's name : "+ft_name).title())
print(("class : "+clas).upper())
print(("roll number : "+rol_no).title())
eng=int(input("enter english marks: "))
maths=int(input("enter maths marks: "))
phy=int(input("enter physics marks: "))
comp=int(input("enter computer marks: "))
chem=int(input("enter chemistry marks: "))
print(("\nstudent name : "+syd_name).title())
print(("father's name : "+ft_name).title())
print(("class : "+clas).upper())
print(("roll number : "+rol_no).title())
obt_marks=eng+maths+phy+comp+chem
tot_marks=500
pert=(obt_marks/tot_marks)*100
print("\nenglish marks: "+str(eng))
print("maths marks: "+str(maths))
print("physics marks: "+str(phy))
print("computer marks: "+str(comp))
print("chemistry marks: "+str(chem))
print("\nyou have obtained "+str(obt_marks) +" out of "+str(tot_marks))
print("you have secured "+str(round(pert,2)))
